name: Publish gradle release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      ## extract stuff about the tag
      - name: Get the version
        id: get_version
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Check output
        env:
          RELEASE_TAG: ${{ steps.vars.outputs.TAG }}
        run: |
          echo ${{ steps.vars.outputs.TAG }}


      # Checkout the code that is associated with *this* release, not the "latest"
      - name: Checkout code @ ${{ steps.vars.outputs.TAG }}
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.TAG }}

      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11


      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}


      # Relies on the version in the build.gradle file in deciding what to push to bintray.
      - name: Publish ${{ steps.vars.outputs.TAG }} to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew bintrayUpload --info


      # Publish the plugin to the Marketplace
      - name: Publish Plugin to Intellij plugin repo
        env:
          PUBLISH_TOKEN: ${{ secrets.INTELLIJ_PLUGIN_PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin --info
