name: Publish gradle release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: windows-latest

    steps:
      ## extract stuff about the tag
      - name: Set output
          id: vars
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_TAG: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_TAG
          echo ${{ steps.vars.outputs.tag }}


      # Checkout the code that is associated with *this* release, not the "latest"
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.tag }}

      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - name: Setup build cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      # Relies on the version in the build.gradle file in deciding what to push to bintray.
      - name: Publish to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew bintrayUpload --info
