name: Publish gradle release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: windows-latest

    steps:
      ## extract stuff about the tag
      - name: Get the version
        id: get_version
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Check output
        env:
          RELEASE_TAG: ${{ steps.vars.outputs.TAG }}
        run: |
          echo ${{ steps.vars.outputs.TAG }}


      # Checkout the code that is associated with *this* release, not the "latest"
      - name: Checkout code @ ${{ steps.vars.outputs.TAG }}
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.vars.outputs.TAG }}

      # Setup Java
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - name: Setup build cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      # Relies on the version in the build.gradle file in deciding what to push to bintray.
      - name: Publish to Bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: ./gradlew bintrayUpload --info
