name: Qodana - License Audit
on:
  workflow_dispatch:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      # clone your project
      - uses: actions/checkout@v3.3.0
      # run qodana-license-audit
      - name: Qodana - License Audit
        uses: jetbrains/qodana-license-audit-action@main
        with:
          options: PYTHON_VERSION=3.7.10
      # upload the results to GitHub artifacts
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/qodana