# Run Qodana inspections
# (originally within build.yml (per plugin template project), but recommended to be in a separate workflow so can be parallelised)

name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v4.2.4
