# Run Qodana inspections
# (originally within build.yml (per plugin template project), but recommended to be in a separate workflow so can be parallelised)

name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - uses: actions/checkout@v3
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v5.0.2
