name: Update Gradle Wrapper

on:
  ## Midnight UTC every day
  schedule:
    - cron: "0 0 * * *"
  ## Option for manual trigger
  workflow_dispatch:

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
